### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by diegoquintanav** [MrMarble/datadis#3]
Hi there! Thanks for the library! 
Are you planning on releasing a new version?

I see there is a broken build in https://github.com/MrMarble/datadis/actions/runs/2476497440 that updates httpx version which is needed in the latest FastAPI and starlette projects.

**Comment by MrMarble** [comment]
Hi! Thank you for using it!

Honestly I don't use this anymore, so was a bit forgotten, but will try to fix it so it works again

**Comment by MrMarble** [comment]
I just updated to the latest version with `poetry update` and tested it with a simple script and everything seems to work. New version released.
I'm closing the issue, if you have any problem comment it and I open it again.
