### ISSUE TITLE
ValueError: Key: accesFare is not available in data.

### ISSUE THREAD

**Issue by atd** [MrMarble/datadis#7]
`get_contract_detail` returns the following error:

```
ValueError: Key: accesFare is not available in data.
```

It seems that value has been removed from the API response

**Comment by garciamaciasjm** [comment]
Any update on that topic ? I am on the same page.

**Comment by MrMarble** [comment]
Ups sorry, I don't use this anymore and the notification got lost between other projects and my job... I'll try to solve it soon
